### ISSUE TITLE
Possible error on Windows? 

### ISSUE THREAD

**Issue by WilliamRettie** [Hyodar/intermediate-axis-theorem#1]
Hi! When I try running this code I get the error:

OSError: exception: access violation reading 0x0000001C

The full traceback is:
Traceback (most recent call last):
  File "C:\Users\wrett\Documents\intermediate-axis-theorem-master\src\main.py", line 76, in <module>
    main()
  File "C:\Users\wrett\Documents\intermediate-axis-theorem-master\src\main.py", line 64, in main
    world.render()
  File "C:\Users\wrett\Documents\intermediate-axis-theorem-master\src\utils\classes\World.py", line 71, in render
    obj.render()
  File "C:\Users\wrett\Documents\intermediate-axis-theorem-master\src\utils\classes\Tbar.py", line 86, in render
    self.handle.render(self.cm, self.handle_relpos)
  File "C:\Users\wrett\Documents\intermediate-axis-theorem-master\src\utils\classes\Cylinder.py", line 56, in render
    glutWireCylinder(self.radius, self.height, self.slices, self.stacks)
OSError: exception: access violation reading 0x0000001C

I'm not an expert with OpenGL at all, so if you could help it would be much appreciated! Thanks!

**Comment by Hyodar** [comment]
Hi, @WilliamRettie!

That's strange.
I found a thread on StackOverflow that seems to have some similarities. The author said he/she didn't run into this problem on their Linux machine, while in Windows the issue appeared.
So, it could make sense, since I only ran this simulation on a Linux machine.

I'm gonna do some testing in a while, but just to make sure:
Have you installed OpenGL and the FreeGLUT packages (as well as the PyOpenGL python library)?

If you didn't, that's a bit my fault as well for not specifying it in the README. The python library used here only wraps the OpenGL and GLUT packages, but those need to be installed separately.

**Comment by WilliamRettie** [comment]
Hi Franco,

Thanks for getting back so quickly! I'll try running it on a Linux machine and see what happens.

As for your question, yes I have all the OpenGL and FreeGLUT packages necessary, but installing them was a bit tricky. From what I read in my research, the typical OpenGL package for Windows is missing some things for FreeGLUT. What I had to do was uninstall the OpenGL package I had, and pip install this custom package which includes all the missing FreeGLUT accessories:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl
If you'd like to include that in the README it would probably help those who want to run it on Windows in the future! No worries though, I should've been running this on a Linux machine anyway. 

Please let me know if you figure out a way to run it on Windows, I'll try running it on Linux. Thanks again for the response!

**Comment by Hyodar** [comment]
I decided to remove GLUT as a dependency since it seems to be related to this issue and I didn't really use it that much.
So, I made some changes in 2e130e8 and refactored all the places I used those resources. Now it's supposed to run normally without GLUT.

Could you test if the latest version works on Windows?

**Comment by WilliamRettie** [comment]
Fantastic! It works perfectly, thank you so much! I just have 2 final quick questions:

1. I'm currently making a video on the intermediate axis theorem, and I'd like to use your code. Is that ok with you? I'll definitely give full credit and leave the github link in the description of the video.
2. Is there a way to separate the graph from the Tbar object, or simply remove the graph? If I could screen record just the tbar and then just the graph it would look much nicer in the finished video. If this is too complicated to explain then no worries, but if you could point me towards where I could do this in the code then it would be much appreciated!

Thank you again so much!

Update: Getting rid of screen.render() on line 64 removes the graph, and leaves only the tbar. I'm looking for ways to display just the graph now.

**Comment by Hyodar** [comment]
Nice!

1. No problem! However, there is one thing to note: this simulation slowly gets more and more innacurate; it's better seen when the speed is increased. I made this based on [another simulation](https://www.youtube.com/watch?v=PY7fRozbrtk) (you could also take a look if this one better suits your needs) and it also suffers from the same problem. The math seems to be right, maybe it's because of some imprecision. If you'll just use the simulation as a visual example for a minute or so this probably won't be a big issue.

2. I separated the `step` functions and `render`, so to render only the graph, just comment the line `world.render()`, and to render only the tbar, just comment the line `screen.render()`.

**Comment by WilliamRettie** [comment]
Awesome, thanks! Yeah I saw James McFarlin's video, but the link to his code is dead and he hasn't been answering my comments to re-upload it. I only plan on using it for about a minute so no worries, but thanks for letting me know! I'll let you know when it's uploaded!
I tried commenting out `world.render()`, and this removes the tbar, but it also removes the lines from the graph. So I'm just left with the x,y,z axis. Would you have an idea of what's causing this? Sorry to be asking so much, thanks for all the help so far!

**Comment by Hyodar** [comment]
Oh, did you also comment `world.step()` or `world.clear()`?
If so, if you comment `world.step()`, there won't be any data to plot, so you should only comment `world.render()`.

**Comment by WilliamRettie** [comment]
Woops, I must've been playing around with an older version. Everything works now, thank you so much! I'll let you know when the video is up, should be soon. Thanks again!
